services:
  gitlab:
    container_name: gitlab
    image: '$ECR_REGISTRY/gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.codebeneath-labs.org'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.codebeneath-labs.org'
        # 'https://...' triggers letsencrypt 'true', so disable since we use certs at the LB
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # gitlab_rails['gitlab_signup_enabled'] = false
        # gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8', '::1/128'] 
      # GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "$RUNNER_REG_TOKEN"
    ports:
      - '80:80'
      # - '443:443'
      # - '22:22'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    healthcheck:
      test: curl -f http://localhost/users/sign_in || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

  # This runner image will pull and run specific runner images declared in .gitlab-ci.yml
  #
  # > Note: Can't get this runner image to work with the ECR credential helper.
  #
  # gitlab-runner:
  #   container_name: gitlab-runner
  #   depends_on:
  #     gitlab:
  #       condition: service_healthy
  #   image: '$ECR_REGISTRY/codebeneath/gitlab/gitlab-runner-ecr-helper:1.0'
  #   entrypoint: [""]
  #   environment:
  #     DOCKER_AUTH_CONFIG: '{ "credsStore": "ecr-login" }'
  #   command: ["/bin/bash", "-c", "gitlab-runner register \
  #                                   --non-interactive \
  #                                   --url 'https://gitlab.codebeneath-labs.org' \
  #                                   --registration-token '$RUNNER_REG_TOKEN' \
  #                                   --executor 'docker' \
  #                                   --docker-image 'python:alpine' \
  #                                   --docker-network-mode 'host' \
  #                                   --tag-list 'python,tf' \
  #                                   --env DOCKER_AUTH_CONFIG='{ \"credsStore\": \"ecr-login\" }' \
  #             && gitlab-runner run --user=gitlab-runner --working-directory=/etc/gitlab-runner"
  #   ]
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #     - '/usr/bin/docker:/usr/bin/docker'
  #   network_mode: 'host'
  #   shm_size: '64m'
